//! Translation dictionary loading and persistence.

use std::fs::{File, OpenOptions};
use std::io::{BufRead, BufReader, Write};
use std::path::{Path, PathBuf};
use std::sync::mpsc;

use rustc_hash::FxHashMap;

use crate::backend::normalize::normalize_key;
use crate::messages::BackendEvent;

#[derive(Default)]
struct LoadedTxtData {
    index: FxHashMap<String, String>,
    source_entries: FxHashMap<String, (String, String)>,
}

fn is_excluded(file_name: &str) -> bool {
    file_name == "_Preprocessors.txt"
        || file_name == "_Postprocessors.txt"
        || file_name == "_Substitutions.txt"
        || file_name.starts_with("_AutoGeneratedTranslations")
}

fn read_txt_into(path: &Path, loaded: &mut LoadedTxtData) -> usize {
    let mut count = 0;

    if let Ok(file) = File::open(path) {
        let reader = BufReader::new(file);
        for line in reader.lines() {
            let line = match line {
                Ok(line) => line,
                Err(_) => continue,
            };

            let line = line.trim_start_matches('\u{feff}').trim();
            if line.is_empty() {
                continue;
            }

            if let Some(index) = line.find('=') {
                let key = line[..index].trim();
                let value = line[index + 1..].trim();
                if !key.is_empty() {
                    let normalized = normalize_key(key);
                    loaded.index.insert(normalized.clone(), value.to_string());
                    loaded
                        .source_entries
                        .insert(normalized, (key.to_string(), value.to_string()));
                    count += 1;
                }
            }
        }
    }

    count
}

fn load_txt_files(root_dir: &Path) -> LoadedTxtData {
    let mut loaded = LoadedTxtData::default();

    let dir_entries = match std::fs::read_dir(root_dir) {
        Ok(entries) => entries,
        Err(_) => return loaded,
    };

    for entry in dir_entries.flatten() {
        let path = entry.path();

        if path.is_file() && path.extension().map(|ext| ext == "txt").unwrap_or(false) {
            let file_name = path
                .file_name()
                .and_then(|name| name.to_str())
                .unwrap_or("");
            if !is_excluded(file_name) {
                read_txt_into(&path, &mut loaded);
            }
            continue;
        }

        if path.is_dir() {
            if let Ok(sub_entries) = std::fs::read_dir(&path) {
                for sub_entry in sub_entries.flatten() {
                    let sub_path = sub_entry.path();
                    if sub_path.is_file()
                        && sub_path
                            .extension()
                            .map(|ext| ext == "txt")
                            .unwrap_or(false)
                    {
                        let sub_name = sub_path
                            .file_name()
                            .and_then(|name| name.to_str())
                            .unwrap_or("");
                        if !is_excluded(sub_name) {
                            read_txt_into(&sub_path, &mut loaded);
                        }
                    }
                }
            }
        }
    }

    loaded
}

fn build_index_from_txt(txt_root: &Path, bin_file: &Path) -> LoadedTxtData {
    let loaded = load_txt_files(txt_root);
    save_index(bin_file, &loaded.index);
    loaded
}

fn save_index(bin_file: &Path, entries: &FxHashMap<String, String>) {
    if let Ok(data) = bincode::serialize(entries) {
        let _ = std::fs::write(bin_file, &data);
    }
}

pub struct Dictionary {
    index: FxHashMap<String, String>,
    source_entries: FxHashMap<String, (String, String)>,
    buffer: Vec<(String, String)>,
    txt_file: PathBuf,
    bin_file: PathBuf,
    event_tx: mpsc::Sender<BackendEvent>,
    pub loaded_entries: usize,
}

impl Dictionary {
    pub fn new(
        txt_root: PathBuf,
        txt_file: PathBuf,
        bin_file: PathBuf,
        event_tx: mpsc::Sender<BackendEvent>,
    ) -> Self {
        if let Some(parent) = txt_file.parent() {
            let _ = std::fs::create_dir_all(parent);
        }

        if !txt_file.exists() {
            if let Ok(mut file) = File::create(&txt_file) {
                let _ = file.write_all(&[0xEF, 0xBB, 0xBF]);
            }
        }

        let loaded = build_index_from_txt(&txt_root, &bin_file);
        let loaded_entries = loaded.index.len();

        let _ = event_tx.send(BackendEvent::DictionaryLoaded(loaded_entries));
        let _ = event_tx.send(BackendEvent::StatisticsUpdate(0, 0));

        Self {
            index: loaded.index,
            source_entries: loaded.source_entries,
            buffer: Vec::new(),
            txt_file,
            bin_file,
            event_tx,
            loaded_entries,
        }
    }

    pub fn lookup(&self, key: &str) -> Option<String> {
        let normalized = normalize_key(key.trim());
        self.index.get(&normalized).cloned()
    }

    pub fn register(&mut self, key: &str, val: &str) {
        let key = key.trim();
        let val = val.trim();
        if key.is_empty() {
            return;
        }

        let normalized = normalize_key(key);
        if self.index.contains_key(&normalized) {
            return;
        }

        self.index.insert(normalized, val.to_string());
        self.source_entries
            .insert(normalize_key(key), (key.to_string(), val.to_string()));
        self.buffer.push((key.to_string(), val.to_string()));
        self.loaded_entries += 1;

        let _ = self.event_tx.send(BackendEvent::DictionaryNewEntry(
            crate::messages::current_timestamp(),
            key.to_string(),
            val.to_string(),
        ));
    }

    #[allow(dead_code)]
    pub fn flush_buffer(&mut self) -> usize {
        if self.buffer.is_empty() {
            return 0;
        }

        if let Some(parent) = self.txt_file.parent() {
            let _ = std::fs::create_dir_all(parent);
        }

        let file_exists = self.txt_file.exists();
        let count = self.buffer.len();

        match OpenOptions::new()
            .create(true)
            .append(true)
            .open(&self.txt_file)
        {
            Ok(mut file) => {
                if !file_exists {
                    let _ = file.write_all(&[0xEF, 0xBB, 0xBF]);
                }
                for (key, value) in &self.buffer {
                    let _ = writeln!(file, "{}={}", key, value);
                }
                self.buffer.clear();

                save_index(&self.bin_file, &self.index);

                let _ = self
                    .event_tx
                    .send(BackendEvent::DictionaryLoaded(self.index.len()));
                count
            }
            Err(_) => 0,
        }
    }
}
