//! Translation dictionary loading and persistence.

use std::fs::{File, OpenOptions};
use std::io::{BufRead, BufReader, Write};
use std::path::{Path, PathBuf};
use std::sync::mpsc;

use ::regex::Regex;
use rustc_hash::FxHashMap;

use crate::messages::{BackendEvent, LogLevel, LogSource, current_timestamp};

pub(crate) const DICT_BIN_MAGIC: &[u8; 8] = b"TENUKI2\0";
pub(crate) const DICT_BIN_VERSION: u32 = 2;
pub(crate) const DICT_BIN_HEADER_LEN: usize = 40;
pub(crate) const DICT_BIN_TABLE_ENTRY_LEN: usize = 16;

#[derive(Clone, Debug, PartialEq, Eq)]
pub(crate) struct EntryOrigin {
    path: PathBuf,
    line_number: usize,
}

#[derive(Clone, Debug)]
struct RawExactEntry {
    source: String,
    value: String,
    origin: EntryOrigin,
    order: u64,
}

#[derive(Clone, Debug, PartialEq, Eq)]
pub(crate) struct AcceptedExactEntry {
    source: String,
    value: String,
}

#[derive(Clone, Debug, Default)]
struct RawTxtData {
    exact_entries: Vec<RawExactEntry>,
    regex_entries: Vec<RawRegexEntry>,
    loaded_files: usize,
    next_order: u64,
}

#[derive(Clone, Debug, Default)]
#[allow(dead_code)]
pub struct DictBuildReport {
    pub raw_exact: usize,
    pub raw_regex: usize,
    pub duplicate_source_dropped: usize,
    pub duplicate_regex_dropped: usize,
    pub regex_covered_exact_dropped: usize,
    pub regex_conflicts: usize,
    pub accepted_exact: usize,
    pub accepted_regex: usize,
    pub loaded_files: usize,
    pub dict_bin_version: u32,
    pub exact_count: usize,
    pub blob_len: usize,
    pub dict_bin_error: Option<String>,
    pub warnings: Vec<String>,
}

#[derive(Clone, Copy, Debug)]
pub(crate) struct ParsedHeader {
    pub(crate) version: u32,
    pub(crate) exact_count: u32,
    pub(crate) exact_table_offset: u64,
    pub(crate) string_blob_offset: u64,
    pub(crate) string_blob_len: u64,
}

pub(crate) mod bin_format;
pub(crate) mod regex;
pub(crate) mod split;
pub(crate) use bin_format::{save_dict_bin, DictBinIndex};
pub(crate) use regex::{compile_regex_entries, is_tenuki_regex_file, try_parse_regex_rule, RawRegexEntry, RegexRule};
pub(crate) use split::{is_tenuki_split_file, load_split_rules, SplitResult, SplitRule};

fn is_excluded(file_name: &str) -> bool {
    file_name == "_Preprocessors.txt"
        || file_name == "_Postprocessors.txt"
        || file_name == "_Substitutions.txt"
        || file_name.starts_with("_AutoGeneratedTranslations")
}

fn is_txt_file(path: &Path) -> bool {
    path.is_file() && path.extension().map(|ext| ext == "txt").unwrap_or(false)
}

fn is_tenuki_dict_file(path: &Path) -> bool {
    path.file_name()
        .and_then(|name| name.to_str())
        .map(|name| name.eq_ignore_ascii_case("Tenuki.dict.txt"))
        .unwrap_or(false)
}

fn is_readable_normal_txt(path: &Path) -> bool {
    if !is_txt_file(path)
        || is_tenuki_dict_file(path)
        || is_tenuki_regex_file(path)
        || is_tenuki_split_file(path)
    {
        return false;
    }
    let file_name = path
        .file_name()
        .and_then(|name| name.to_str())
        .unwrap_or("");
    !is_excluded(file_name)
}

pub(crate) fn sorted_dir_entries(root_dir: &Path) -> Vec<PathBuf> {
    let mut paths = std::fs::read_dir(root_dir)
        .map(|entries| {
            entries
                .flatten()
                .map(|entry| entry.path())
                .collect::<Vec<PathBuf>>()
        })
        .unwrap_or_default();
    paths.sort_by(|a, b| a.to_string_lossy().cmp(&b.to_string_lossy()));
    paths
}

fn read_txt_into(path: &Path, loaded: &mut RawTxtData) -> usize {
    let mut count = 0;

    if let Ok(file) = File::open(path) {
        let reader = BufReader::new(file);
        loaded.loaded_files += 1;
        for (line_index, line) in reader.lines().enumerate() {
            let line = match line {
                Ok(line) => line,
                Err(_) => continue,
            };

            let line = if line_index == 0 {
                line.strip_prefix('\u{feff}').unwrap_or(&line)
            } else {
                &line
            };
            if line.trim().is_empty() {
                continue;
            }

            if let Some((pattern, replacement)) = try_parse_regex_rule(line) {
                loaded.next_order += 1;
                loaded.regex_entries.push(RawRegexEntry {
                    pattern,
                    replacement,
                    origin: EntryOrigin {
                        path: path.to_path_buf(),
                        line_number: line_index + 1,
                    },
                    order: loaded.next_order,
                });
                count += 1;
                continue;
            }

            if let Some((key, value)) = line.split_once('=') {
                if !key.is_empty() {
                    loaded.next_order += 1;
                    loaded.exact_entries.push(RawExactEntry {
                        source: key.to_string(),
                        value: value.to_string(),
                        origin: EntryOrigin {
                            path: path.to_path_buf(),
                            line_number: line_index + 1,
                        },
                        order: loaded.next_order,
                    });
                    count += 1;
                }
            }
        }
    }

    count
}

fn load_txt_files(root_dir: &Path) -> RawTxtData {
    let mut loaded = RawTxtData::default();
    let root_entries = sorted_dir_entries(root_dir);

    for path in root_entries.iter().filter(|path| path.is_dir()) {
        for sub_path in sorted_dir_entries(path) {
            if is_readable_normal_txt(&sub_path) {
                read_txt_into(&sub_path, &mut loaded);
            }
        }
    }

    for path in root_entries
        .iter()
        .filter(|path| is_readable_normal_txt(path))
    {
        read_txt_into(path, &mut loaded);
    }

    let tenuki_dict = root_dir.join("Tenuki.dict.txt");
    if tenuki_dict.exists() {
        read_txt_into(&tenuki_dict, &mut loaded);
    }

    let tenuki_regex = root_dir.join("Tenuki.regex.txt");
    if tenuki_regex.exists() {
        read_txt_into(&tenuki_regex, &mut loaded);
    }

    loaded
}

fn collect_value_index(entries: &[AcceptedExactEntry]) -> FxHashMap<String, String> {
    let mut value_index = FxHashMap::default();
    for entry in entries {
        // Value observation index: accepted exact raw value -> same raw value.
        // It is built from accepted exact entries, but it is not dict.bin source authority.
        if !entry.value.is_empty() {
            value_index
                .entry(entry.value.clone())
                .or_insert_with(|| entry.value.clone());
        }
    }
    value_index
}

fn accepted_exact_entries(
    raw_exact: &[RawExactEntry],
    regex_rules: &[RegexRule],
    report: &mut DictBuildReport,
) -> Vec<AcceptedExactEntry> {
    let mut by_source: FxHashMap<String, RawExactEntry> = FxHashMap::default();
    for entry in raw_exact {
        let _ = &entry.origin;
        if by_source
            .insert(entry.source.clone(), entry.clone())
            .is_some()
        {
            report.duplicate_source_dropped += 1;
        }
    }

    let mut deduped = by_source.into_values().collect::<Vec<_>>();
    deduped.sort_by_key(|entry| entry.order);

    let mut accepted = Vec::new();
    for entry in deduped {
        let mut covered = false;
        for rule in regex_rules {
            if let Some(caps) = rule.pattern.captures(&entry.source) {
                let mut expanded = String::new();
                caps.expand(&rule.replacement, &mut expanded);
                if expanded == entry.value {
                    report.regex_covered_exact_dropped += 1;
                    covered = true;
                    break;
                }
                report.regex_conflicts += 1;
            }
        }
        if !covered {
            accepted.push(AcceptedExactEntry {
                source: entry.source,
                value: entry.value,
            });
        }
    }

    accepted.sort_by(|a, b| a.source.cmp(&b.source));
    report.accepted_exact = accepted.len();
    accepted
}

fn build_entry_sets(txt_root: &Path) -> (Vec<AcceptedExactEntry>, Vec<RegexRule>, DictBuildReport) {
    let raw = load_txt_files(txt_root);
    let mut report = DictBuildReport {
        raw_exact: raw.exact_entries.len(),
        raw_regex: raw.regex_entries.len(),
        loaded_files: raw.loaded_files,
        ..Default::default()
    };

    let regex_rules = compile_regex_entries(&raw.regex_entries, &mut report);
    let exact_entries = accepted_exact_entries(&raw.exact_entries, &regex_rules, &mut report);

    (exact_entries, regex_rules, report)
}

fn ensure_bom_file(path: &Path) {
    if let Some(parent) = path.parent() {
        let _ = std::fs::create_dir_all(parent);
    }

    if !path.exists() {
        if let Ok(mut file) = File::create(path) {
            let _ = file.write_all(&[0xEF, 0xBB, 0xBF]);
        }
    }
}

pub struct Dictionary {
    exact_index: Option<DictBinIndex>,
    value_index: FxHashMap<String, String>,
    regex_rules: Vec<RegexRule>,
    split_rules: Vec<SplitRule>,
    exact_buffer: Vec<(String, String)>,
    regex_buffer: Vec<(String, String)>,
    txt_root: PathBuf,
    exact_txt_file: PathBuf,
    regex_txt_file: PathBuf,
    bin_file: PathBuf,
    event_tx: mpsc::Sender<BackendEvent>,
    pub loaded_entries: usize,
    pub build_report: DictBuildReport,
}

impl Dictionary {
    fn build_exact_index(
        bin_file: &Path,
        exact_entries: &[AcceptedExactEntry],
        build_report: &mut DictBuildReport,
    ) -> Option<DictBinIndex> {
        build_report.dict_bin_version = DICT_BIN_VERSION;

        let blob_len = match save_dict_bin(bin_file, exact_entries) {
            Ok(blob_len) => blob_len,
            Err(e) => {
                let message = format!("dict.bin write failed ({}): {}", bin_file.display(), e);
                log::warn!("{}", message);
                build_report.exact_count = 0;
                build_report.blob_len = 0;
                build_report.dict_bin_error = Some(message);
                return None;
            }
        };

        match DictBinIndex::open(bin_file) {
            Ok(index) => {
                build_report.exact_count = index.header.exact_count as usize;
                build_report.blob_len = blob_len;
                build_report.dict_bin_error = None;
                Some(index)
            }
            Err(e) => {
                let message = format!("dict.bin open failed ({}): {}", bin_file.display(), e);
                log::warn!("{}", message);
                build_report.exact_count = 0;
                build_report.blob_len = blob_len;
                build_report.dict_bin_error = Some(message);
                None
            }
        }
    }

    pub fn new(
        txt_root: PathBuf,
        exact_txt_file: PathBuf,
        regex_txt_file: PathBuf,
        split_txt_file: PathBuf,
        bin_file: PathBuf,
        event_tx: mpsc::Sender<BackendEvent>,
    ) -> Self {
        ensure_bom_file(&exact_txt_file);
        ensure_bom_file(&regex_txt_file);
        ensure_bom_file(&split_txt_file);

        let (exact_entries, regex_rules, mut build_report) = build_entry_sets(&txt_root);
        let (split_rules, split_warnings) = load_split_rules(&txt_root);
        let value_index = collect_value_index(&exact_entries);
        let exact_index = Self::build_exact_index(&bin_file, &exact_entries, &mut build_report);
        let loaded_entries = build_report.exact_count + build_report.accepted_regex;

        let _ = event_tx.send(BackendEvent::DictionaryLoaded(loaded_entries));
        let _ = event_tx.send(BackendEvent::StatisticsUpdate(0, 0));

        let mut total_warnings = 0;
        for w in build_report.warnings.iter().chain(split_warnings.iter()) {
            total_warnings += 1;
            let _ = event_tx.send(BackendEvent::Log(
                LogSource::Tenuki,
                w.clone(),
                LogLevel::Info,
                current_timestamp(),
            ));
        }
        if total_warnings == 0 {
            let _ = event_tx.send(BackendEvent::Log(
                LogSource::Tenuki,
                "[Dict] load OK, no errors".to_string(),
                LogLevel::Success,
                current_timestamp(),
            ));
        }

        Self {
            exact_index,
            value_index,
            regex_rules,
            split_rules,
            exact_buffer: Vec::new(),
            regex_buffer: Vec::new(),
            txt_root,
            exact_txt_file,
            regex_txt_file,
            bin_file,
            event_tx,
            loaded_entries,
            build_report,
        }
    }

    fn rebuild_from_txt(&mut self) {
        let (exact_entries, regex_rules, mut build_report) = build_entry_sets(&self.txt_root);
        self.exact_index = None;
        self.exact_index =
            Self::build_exact_index(&self.bin_file, &exact_entries, &mut build_report);

        self.value_index = collect_value_index(&exact_entries);
        self.regex_rules = regex_rules;
        let (split_rules, split_warnings) = load_split_rules(&self.txt_root);
        self.split_rules = split_rules;
        self.loaded_entries = build_report.exact_count + build_report.accepted_regex;
        self.build_report = build_report;

        let mut total_warnings = 0;
        for w in self.build_report.warnings.iter().chain(split_warnings.iter()) {
            total_warnings += 1;
            let _ = self.event_tx.send(BackendEvent::Log(
                LogSource::Tenuki,
                w.clone(),
                LogLevel::Info,
                current_timestamp(),
            ));
        }
        if total_warnings == 0 {
            let _ = self.event_tx.send(BackendEvent::Log(
                LogSource::Tenuki,
                "[Dict] load OK, no errors".to_string(),
                LogLevel::Success,
                current_timestamp(),
            ));
        }
    }

    pub fn lookup_source(&self, key: &str) -> Option<String> {
        if let Some(hit) = self
            .exact_index
            .as_ref()
            .and_then(|index| index.lookup(key))
        {
            return Some(hit);
        }

        for rule in &self.regex_rules {
            if let Some(caps) = rule.pattern.captures(key) {
                let mut out = String::new();
                caps.expand(&rule.replacement, &mut out);
                return Some(out);
            }
        }
        None
    }

    pub fn lookup_split(&self, key: &str) -> Option<SplitResult> {
        for rule in &self.split_rules {
            let caps = match rule.pattern.captures(key) {
                Some(c) => c,
                None => continue,
            };
            let m = match caps.get(0) {
                Some(m) => m,
                None => continue,
            };
            let full_start = m.start();
            let full_end = m.end();
            let inner_groups: Vec<Option<(usize, usize)>> = caps
                .iter()
                .skip(1)
                .map(|g| g.map(|m| (m.start(), m.end())))
                .collect();
            let replacement = {
                let mut tmpl = rule.replacement.clone();
                tmpl = tmpl.replace("$S", "$$S");
                tmpl = tmpl.replace("$L", "$$L");
                tmpl = tmpl.replace("$R", "$$R");
                let mut expanded = String::new();
                caps.expand(&tmpl, &mut expanded);
                expanded
            };

            let result = SplitResult {
                full_match_start: full_start,
                full_match_end: full_end,
                inner_groups,
                replacement,
            };

            log::info!(
                "[SPLIT_LOOKUP] key=\"{}\" hit=true pattern=\"{}\" match_len={}",
                key, rule.source_pattern, full_end - full_start
            );
            return Some(result);
        }

        log::info!("[SPLIT_LOOKUP] key=\"{}\" hit=false", key);
        None
    }

    pub fn lookup_value(&self, text: &str) -> Option<String> {
        // Raw value observation lookup only; source lookup stays in lookup_source.
        self.value_index.get(text).cloned()
    }

    pub fn register(&mut self, key: &str, val: &str) {
        if key.is_empty() {
            return;
        }

        if let Some((pattern, replacement)) = try_parse_regex_rule(&format!("{key}={val}")) {
            let already_registered = self.regex_rules.iter().any(|r| r.source_pattern == pattern);
            if !already_registered {
                match Regex::new(&pattern) {
                    Ok(re) => {
                        self.regex_rules.push(RegexRule {
                            pattern: re,
                            replacement: replacement.clone(),
                            source_pattern: pattern.clone(),
                        });
                        self.loaded_entries += 1;
                    }
                    Err(e) => {
                        log::debug!("regex register failed: {} -> {} ({})", key, val, e);
                        return;
                    }
                }
            }

            self.regex_buffer
                .push((pattern.clone(), replacement.clone()));
            let _ = self.event_tx.send(BackendEvent::DictionaryNewEntry(
                crate::messages::current_timestamp(),
                key.to_string(),
                val.to_string(),
            ));
            return;
        }

        if self
            .exact_index
            .as_ref()
            .and_then(|index| index.lookup(key))
            .is_some()
            || self
                .exact_buffer
                .iter()
                .any(|(buffer_key, _)| buffer_key == key)
        {
            return;
        }

        self.exact_buffer.push((key.to_string(), val.to_string()));
        self.loaded_entries += 1;

        let _ = self.event_tx.send(BackendEvent::DictionaryNewEntry(
            crate::messages::current_timestamp(),
            key.to_string(),
            val.to_string(),
        ));
    }

    pub fn register_regex_rule(&mut self, pattern: String, replacement: String) -> bool {
        if self.regex_rules.iter().any(|r| r.source_pattern == pattern) {
            return false;
        }
        match Regex::new(&pattern) {
            Ok(re) => {
                self.regex_rules.push(RegexRule {
                    pattern: re,
                    replacement,
                    source_pattern: pattern,
                });
                self.loaded_entries += 1;
                true
            }
            Err(e) => {
                log::debug!("regex register failed: {} - {}", pattern, e);
                false
            }
        }
    }

    #[allow(dead_code)]
    pub fn flush_buffer(&mut self) -> usize {
        if self.exact_buffer.is_empty() && self.regex_buffer.is_empty() {
            return 0;
        }

        let exact_count = self.exact_buffer.len();
        let regex_count = self.regex_buffer.len();

        if exact_count > 0 {
            ensure_bom_file(&self.exact_txt_file);
            let exact_exists = self.exact_txt_file.exists();
            match OpenOptions::new()
                .create(true)
                .append(true)
                .open(&self.exact_txt_file)
            {
                Ok(mut file) => {
                    if !exact_exists {
                        let _ = file.write_all(&[0xEF, 0xBB, 0xBF]);
                    }
                    for (key, value) in &self.exact_buffer {
                        let _ = writeln!(file, "{}={}", key, value);
                    }
                    self.exact_buffer.clear();
                }
                Err(_) => return 0,
            }
        }

        if regex_count > 0 {
            ensure_bom_file(&self.regex_txt_file);
            let regex_exists = self.regex_txt_file.exists();
            match OpenOptions::new()
                .create(true)
                .append(true)
                .open(&self.regex_txt_file)
            {
                Ok(mut file) => {
                    if !regex_exists {
                        let _ = file.write_all(&[0xEF, 0xBB, 0xBF]);
                    }
                    for (pattern, replacement) in &self.regex_buffer {
                        let _ = writeln!(file, "r:\"{}\"={}", pattern, replacement);
                    }
                    self.regex_buffer.clear();
                }
                Err(_) => return 0,
            }
        }

        self.rebuild_from_txt();

        let _ = self
            .event_tx
            .send(BackendEvent::DictionaryLoaded(self.loaded_entries));

        exact_count + regex_count
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::io::Write;
    use std::sync::mpsc;

    fn unique_tmp(name: &str) -> PathBuf {
        let unique = std::time::SystemTime::now()
            .duration_since(std::time::UNIX_EPOCH)
            .unwrap()
            .as_nanos();
        std::env::temp_dir().join(format!("tenuki_dict_{}_{}", name, unique))
    }

    fn write_txt(path: &Path, lines: &[&str]) {
        if let Some(parent) = path.parent() {
            std::fs::create_dir_all(parent).unwrap();
        }
        let mut file = std::fs::File::create(path).unwrap();
        file.write_all(b"\xEF\xBB\xBF").unwrap();
        for line in lines {
            writeln!(file, "{}", line).unwrap();
        }
    }

    fn make_dict(tmp: &Path, rules: &[&str]) -> Dictionary {
        std::fs::create_dir_all(tmp).unwrap();
        write_txt(&tmp.join("rules.txt"), rules);
        let (tx, _rx) = mpsc::channel();
        Dictionary::new(
            tmp.to_path_buf(),
            tmp.join("Tenuki.dict.txt"),
            tmp.join("Tenuki.regex.txt"),
            tmp.join("Tenuki.split.txt"),
            tmp.join("dict.bin"),
            tx,
        )
    }

    #[test]
    fn dict_bin_lookup_hits_exact_index() {
        let tmp = unique_tmp("bin_exact");
        let dict = make_dict(&tmp, &["hello=bonjour"]);

        assert_eq!(dict.lookup_source("hello"), Some("bonjour".to_string()));
        assert_eq!(dict.build_report.dict_bin_version, DICT_BIN_VERSION);
        assert_eq!(dict.build_report.accepted_exact, 1);
        assert_eq!(dict.build_report.exact_count, 1);
        assert!(dict.build_report.blob_len > 0);

        let _ = std::fs::remove_dir_all(tmp);
    }

    #[test]
    fn dict_bin_write_failure_makes_runtime_exact_count_zero() {
        let tmp = unique_tmp("bin_write_failure");
        write_txt(
            &tmp.join("root.txt"),
            &["hello=bonjour", r#"r:"^HP([0-9]+)$"=Health$1"#],
        );
        let bin_path = tmp.join("dict.bin");
        std::fs::create_dir_all(&bin_path).unwrap();

        let (tx, rx) = mpsc::channel();
        let dict = Dictionary::new(
            tmp.clone(),
            tmp.join("Tenuki.dict.txt"),
            tmp.join("Tenuki.regex.txt"),
            tmp.join("Tenuki.split.txt"),
            bin_path,
            tx,
        );

        assert_eq!(dict.build_report.accepted_exact, 1);
        assert_eq!(dict.build_report.exact_count, 0);
        assert!(dict.build_report.dict_bin_error.is_some());
        assert_eq!(dict.lookup_source("hello"), None);
        assert_eq!(dict.lookup_source("HP12"), Some("Health12".to_string()));
        assert!(matches!(
            rx.try_recv(),
            Ok(BackendEvent::DictionaryLoaded(1))
        ));

        let _ = std::fs::remove_dir_all(tmp);
    }

    #[test]
    fn reads_subdir_root_tenuki_dict_then_tenuki_regex_order() {
        let tmp = unique_tmp("read_order");
        write_txt(&tmp.join("sub").join("a.txt"), &["same=sub"]);
        write_txt(&tmp.join("root.txt"), &["same=root"]);
        write_txt(&tmp.join("Tenuki.dict.txt"), &["same=tenuki"]);
        write_txt(&tmp.join("Tenuki.regex.txt"), &[r#"r:"^same$"=regex"#]);

        let (tx, _rx) = mpsc::channel();
        let dict = Dictionary::new(
            tmp.clone(),
            tmp.join("Tenuki.dict.txt"),
            tmp.join("Tenuki.regex.txt"),
            tmp.join("Tenuki.split.txt"),
            tmp.join("dict.bin"),
            tx,
        );

        assert_eq!(dict.lookup_source("same"), Some("tenuki".to_string()));
        assert_eq!(dict.build_report.raw_exact, 3);
        assert_eq!(dict.build_report.duplicate_source_dropped, 2);
        assert_eq!(dict.build_report.regex_conflicts, 1);

        let _ = std::fs::remove_dir_all(tmp);
    }

    #[test]
    fn exact_keys_preserve_case_and_edge_spaces() {
        let tmp = unique_tmp("raw_exact");
        write_txt(
            &tmp.join("root.txt"),
            &[
                "ATK=upper",
                "atk=lower",
                "ATK =space-key",
                " trim = spaced value ",
            ],
        );

        let (tx, _rx) = mpsc::channel();
        let dict = Dictionary::new(
            tmp.clone(),
            tmp.join("Tenuki.dict.txt"),
            tmp.join("Tenuki.regex.txt"),
            tmp.join("Tenuki.split.txt"),
            tmp.join("dict.bin"),
            tx,
        );

        assert_eq!(dict.lookup_source("ATK"), Some("upper".to_string()));
        assert_eq!(dict.lookup_source("atk"), Some("lower".to_string()));
        assert_eq!(dict.lookup_source("ATK "), Some("space-key".to_string()));
        assert_eq!(
            dict.lookup_source(" trim "),
            Some(" spaced value ".to_string())
        );
        assert_eq!(dict.lookup_source("trim"), None);
        assert_eq!(dict.build_report.duplicate_source_dropped, 0);
        assert_eq!(dict.build_report.exact_count, 4);

        let _ = std::fs::remove_dir_all(tmp);
    }

    #[test]
    fn regex_duplicate_uses_later_regex_entry() {
        let tmp = unique_tmp("regex_duplicate");
        write_txt(&tmp.join("root.txt"), &[r#"r:"^ATK([0-9]+)$"=old$1"#]);
        write_txt(
            &tmp.join("Tenuki.regex.txt"),
            &[r#"r:"^ATK([0-9]+)$"=new$1"#],
        );

        let (tx, _rx) = mpsc::channel();
        let dict = Dictionary::new(
            tmp.clone(),
            tmp.join("Tenuki.dict.txt"),
            tmp.join("Tenuki.regex.txt"),
            tmp.join("Tenuki.split.txt"),
            tmp.join("dict.bin"),
            tx,
        );

        assert_eq!(dict.lookup_source("ATK12"), Some("new12".to_string()));
        assert_eq!(dict.build_report.duplicate_regex_dropped, 1);

        let _ = std::fs::remove_dir_all(tmp);
    }

    #[test]
    fn regex_covered_exact_is_not_written_to_exact_index() {
        let tmp = unique_tmp("regex_covered");
        write_txt(&tmp.join("root.txt"), &["ATK12=Attack12"]);
        write_txt(
            &tmp.join("Tenuki.regex.txt"),
            &[r#"r:"^ATK([0-9]+)$"=Attack$1"#],
        );

        let (tx, _rx) = mpsc::channel();
        let dict = Dictionary::new(
            tmp.clone(),
            tmp.join("Tenuki.dict.txt"),
            tmp.join("Tenuki.regex.txt"),
            tmp.join("Tenuki.split.txt"),
            tmp.join("dict.bin"),
            tx,
        );

        assert_eq!(dict.lookup_source("ATK12"), Some("Attack12".to_string()));
        assert_eq!(dict.build_report.regex_covered_exact_dropped, 1);
        assert_eq!(dict.build_report.accepted_exact, 0);
        assert_eq!(dict.build_report.exact_count, 0);

        let _ = std::fs::remove_dir_all(tmp);
    }

    #[test]
    fn regex_conflict_keeps_exact_in_index() {
        let tmp = unique_tmp("regex_conflict");
        write_txt(&tmp.join("root.txt"), &["ATK12=Exact12"]);
        write_txt(
            &tmp.join("Tenuki.regex.txt"),
            &[r#"r:"^ATK([0-9]+)$"=Regex$1"#],
        );

        let (tx, _rx) = mpsc::channel();
        let dict = Dictionary::new(
            tmp.clone(),
            tmp.join("Tenuki.dict.txt"),
            tmp.join("Tenuki.regex.txt"),
            tmp.join("Tenuki.split.txt"),
            tmp.join("dict.bin"),
            tx,
        );

        assert_eq!(dict.lookup_source("ATK12"), Some("Exact12".to_string()));
        assert_eq!(dict.build_report.regex_conflicts, 1);
        assert_eq!(dict.build_report.accepted_exact, 1);
        assert_eq!(dict.build_report.exact_count, 1);

        let _ = std::fs::remove_dir_all(tmp);
    }

    #[test]
    fn exact_miss_falls_back_to_regex() {
        let tmp = unique_tmp("regex_fallback");
        let dict = make_dict(&tmp, &[r#"r:"^HP([+-][0-9]+)$"=Health$1"#]);

        assert_eq!(dict.lookup_source("HP+10"), Some("Health+10".to_string()));
        assert_eq!(dict.lookup_source("MP+10"), None);

        let _ = std::fs::remove_dir_all(tmp);
    }

    #[test]
    fn lookup_value_uses_raw_value_exact_match() {
        let tmp = unique_tmp("raw_value");
        write_txt(&tmp.join("root.txt"), &["source= Value "]);

        let (tx, _rx) = mpsc::channel();
        let dict = Dictionary::new(
            tmp.clone(),
            tmp.join("Tenuki.dict.txt"),
            tmp.join("Tenuki.regex.txt"),
            tmp.join("Tenuki.split.txt"),
            tmp.join("dict.bin"),
            tx,
        );

        assert_eq!(dict.lookup_value(" Value "), Some(" Value ".to_string()));
        assert_eq!(dict.lookup_value("value"), None);
        assert_eq!(dict.lookup_value("Value"), None);

        let _ = std::fs::remove_dir_all(tmp);
    }

    #[test]
    fn new_provisions_tenuki_files_without_generic_dict_txt() {
        let tmp = unique_tmp("provision");
        std::fs::create_dir_all(&tmp).unwrap();

        let (tx, _rx) = mpsc::channel();
        let _dict = Dictionary::new(
            tmp.clone(),
            tmp.join("Tenuki.dict.txt"),
            tmp.join("Tenuki.regex.txt"),
            tmp.join("Tenuki.split.txt"),
            tmp.join("dict.bin"),
            tx,
        );

        assert!(tmp.join("Tenuki.dict.txt").exists());
        assert!(tmp.join("Tenuki.regex.txt").exists());
        assert!(tmp.join("Tenuki.split.txt").exists());
        assert!(std::fs::read(tmp.join("Tenuki.dict.txt"))
            .unwrap()
            .starts_with(b"\xEF\xBB\xBF"));
        assert!(std::fs::read(tmp.join("Tenuki.regex.txt"))
            .unwrap()
            .starts_with(b"\xEF\xBB\xBF"));
        assert!(!tmp.join("dict.txt").exists());

        let _ = std::fs::remove_dir_all(tmp);
    }

    #[test]
    fn new_loads_existing_generic_dict_txt_as_input() {
        let tmp = unique_tmp("generic_dict");
        write_txt(&tmp.join("dict.txt"), &["legacy=value"]);

        let (tx, _rx) = mpsc::channel();
        let dict = Dictionary::new(
            tmp.clone(),
            tmp.join("Tenuki.dict.txt"),
            tmp.join("Tenuki.regex.txt"),
            tmp.join("Tenuki.split.txt"),
            tmp.join("dict.bin"),
            tx,
        );

        assert_eq!(dict.lookup_source("legacy"), Some("value".to_string()));

        let _ = std::fs::remove_dir_all(tmp);
    }

    #[test]
    fn register_regex_rule_hits_same_session() {
        let tmp = unique_tmp("live_regex");
        let mut dict = make_dict(&tmp, &[]);

        assert_eq!(dict.lookup_source("SKILL+10"), None);
        assert!(
            dict.register_regex_rule("^SKILL([+-][0-9]+)$".to_string(), "Ability$1".to_string(),)
        );
        assert_eq!(
            dict.lookup_source("SKILL+10"),
            Some("Ability+10".to_string())
        );

        let _ = std::fs::remove_dir_all(tmp);
    }

    #[test]
    fn flush_buffer_saves_entries_rebuilds_bin_and_reopens_lookup() {
        let tmp = unique_tmp("flush");
        std::fs::create_dir_all(&tmp).unwrap();

        let (tx, _rx) = mpsc::channel();
        let mut dict = Dictionary::new(
            tmp.clone(),
            tmp.join("Tenuki.dict.txt"),
            tmp.join("Tenuki.regex.txt"),
            tmp.join("Tenuki.split.txt"),
            tmp.join("dict.bin"),
            tx,
        );

        dict.register("hello", "bonjour");
        dict.register(r#"r:"^ATK([0-9]+)$""#, "Attack$1");
        assert_eq!(dict.lookup_source("hello"), None);
        assert_eq!(dict.flush_buffer(), 2);

        assert_eq!(dict.lookup_source("hello"), Some("bonjour".to_string()));
        assert_eq!(dict.lookup_source("ATK12"), Some("Attack12".to_string()));
        assert_eq!(dict.build_report.accepted_exact, 1);
        assert_eq!(dict.build_report.accepted_regex, 1);

        let exact = std::fs::read_to_string(tmp.join("Tenuki.dict.txt")).unwrap();
        let regex = std::fs::read_to_string(tmp.join("Tenuki.regex.txt")).unwrap();

        assert!(exact.contains("hello=bonjour"));
        assert!(!exact.contains("Attack$1"));
        assert!(regex.contains(r#"r:"^ATK([0-9]+)$"=Attack$1"#));
        assert!(!regex.contains("hello=bonjour"));

        let _ = std::fs::remove_dir_all(tmp);
    }

    #[test]
    fn register_flush_preserves_key_and_value_bytes() {
        let tmp = unique_tmp("flush_raw");
        std::fs::create_dir_all(&tmp).unwrap();

        let (tx, _rx) = mpsc::channel();
        let mut dict = Dictionary::new(
            tmp.clone(),
            tmp.join("Tenuki.dict.txt"),
            tmp.join("Tenuki.regex.txt"),
            tmp.join("Tenuki.split.txt"),
            tmp.join("dict.bin"),
            tx,
        );

        dict.register(" raw ", " Value ");
        assert_eq!(dict.flush_buffer(), 1);

        assert_eq!(dict.lookup_source(" raw "), Some(" Value ".to_string()));
        assert_eq!(dict.lookup_source("raw"), None);

        let exact = std::fs::read_to_string(tmp.join("Tenuki.dict.txt")).unwrap();
        assert!(exact.contains(" raw = Value "));
        assert!(!exact.contains("raw=Value"));

        let _ = std::fs::remove_dir_all(tmp);
    }

    #[test]
    fn split_rule_caret_anchor_matches_start_of_fragment() {
        let tmp = unique_tmp("split_caret");
        let split_path = tmp.join("Tenuki.split.txt");
        std::fs::create_dir_all(&tmp).unwrap();
        let mut f = std::fs::File::create(&split_path).unwrap();
        f.write_all(b"\xEF\xBB\xBF").unwrap();
        writeln!(f, "s:\"^你结识了\"=$Rの人と知り合う").unwrap();
        drop(f);

        let (tx, _rx) = mpsc::channel();
        let dict = Dictionary::new(
            tmp.clone(),
            tmp.join("Tenuki.dict.txt"),
            tmp.join("Tenuki.regex.txt"),
            split_path,
            tmp.join("dict.bin"),
            tx,
        );

        // Fragment that starts with the matched text
        let sr = dict.lookup_split("你结识了武当派");
        assert!(sr.is_some(), "should match: 你结识了武当派");
        let sr = sr.unwrap();
        assert_eq!(sr.replacement, "$Rの人と知り合う");
        assert_eq!(sr.full_match_start, 0);
        assert!(sr.inner_groups.is_empty());

        // Fragment with more text after the match
        let sr2 = dict.lookup_split("你结识了武当派外门弟子凤藤虚");
        assert!(sr2.is_some(), "should match longer fragment");

        // Fragment that does NOT start with the match
        assert!(dict.lookup_split("武当派你结识了").is_none());

        let _ = std::fs::remove_dir_all(tmp);
    }
}
